#!/usr/bin/env bash
# hillclimb-cam installer. Provisions a Raspberry Pi as an SRT camera node that
# publishes to a MediaMTX hub. Interactive. Run on the camera Pi:
#
#     sudo ./install.sh
#
# Idempotent: re-run to reconfigure or add another camera path.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN_DST=/usr/local/bin
UNIT_DST=/etc/systemd/system

[ "$(id -u)" -eq 0 ] || { echo "Run as root:  sudo ./install.sh"; exit 1; }
RUN_USER="${SUDO_USER:-root}"

ask() {  # ask VAR "prompt" ["default"]
  # Honors a preset environment variable (unattended runs:
  # `sudo CAM_PATH=cam1 HUB_HOST=... ./install.sh`) and falls back to the default
  # when there is no controlling terminal (piped / over ssh without a tty).
  local __var="$1" __prompt="$2" __default="${3:-}" __reply
  if [ -n "${!__var:-}" ]; then
    echo "$__prompt: ${!__var} (preset)"; return
  fi
  if [ ! -r /dev/tty ]; then
    printf -v "$__var" '%s' "$__default"
    echo "$__prompt: ${__default:-<empty>} (non-interactive default)"; return
  fi
  read -rp "$__prompt${__default:+ [$__default]}: " __reply </dev/tty
  printf -v "$__var" '%s' "${__reply:-$__default}"
}

echo "== hillclimb-cam installer =="
echo "Encoder service will run as user: $RUN_USER"
echo

# --- dependencies -----------------------------------------------------------
missing=()
command -v ffmpeg   >/dev/null 2>&1 || missing+=(ffmpeg)
command -v v4l2-ctl >/dev/null 2>&1 || missing+=(v4l-utils)
if [ "${#missing[@]}" -gt 0 ]; then
  echo "Missing packages: ${missing[*]}"
  ask INSTALL_DEPS "Install them now with apt? (y/n)" y
  if [ "$INSTALL_DEPS" = y ]; then
    apt-get update && apt-get install -y "${missing[@]}"
  else
    echo "Cannot continue without: ${missing[*]}"; exit 1
  fi
fi

# --- camera + capability probe ----------------------------------------------
echo; echo "-- detected cameras & encode capability --"
bash "$REPO_DIR/bin/probe-camera.sh" || true
echo

# --- config -----------------------------------------------------------------
ask CAM_PATH "MediaMTX path / instance (cam2, cam3, ... — cam1 is picam1)" cam2
ask HUB_HOST "Hub IP (the van's MediaMTX)" 192.168.42.178

# USB cameras only, deduped by resolved node (skip the platform codec nodes; the
# Pi lists each USB cam under two controller aliases that map to the same device).
shopt -s nullglob
declare -A seen_dev
DEVS=()
for dev in /dev/v4l/by-path/*usb*-video-index0; do
  real="$(readlink -f "$dev")"
  [ -n "${seen_dev[$real]:-}" ] && continue
  seen_dev[$real]=1
  DEVS+=("$dev")
done
shopt -u nullglob
if [ -n "${CAM_DEVICE:-}" ]; then
  echo "Camera device (preset): $CAM_DEVICE"
elif [ "${#DEVS[@]}" -eq 0 ]; then
  ask CAM_DEVICE "Camera device path" /dev/video0
elif [ "${#DEVS[@]}" -eq 1 ]; then
  CAM_DEVICE="${DEVS[0]}"; echo "Camera device: $CAM_DEVICE"
else
  echo "Multiple cameras found:"; i=0
  for d in "${DEVS[@]}"; do echo "  [$i] $d"; i=$((i+1)); done
  ask IDX "Pick a camera index" 0; CAM_DEVICE="${DEVS[$IDX]}"
fi

ask CAM_INPUT_FORMAT "Input format (yuyv422 / mjpeg / h264)" yuyv422
ask CAM_W       "Width"      1280
ask CAM_H       "Height"     720
ask CAM_FPS     "Frame rate" 10
ask CAM_BITRATE "Bitrate"    2500k

if   [ "$CAM_INPUT_FORMAT" = h264 ]; then DEF_ENC=copy
elif [ -e /dev/video11 ];            then DEF_ENC=h264_v4l2m2m
else                                      DEF_ENC=libx264; fi
ask CAM_ENCODER "Encoder (auto/h264_v4l2m2m/libx264/copy)" "$DEF_ENC"

# --- write env file ---------------------------------------------------------
ENV_FILE="/etc/default/cam-stream-${CAM_PATH}"
cat > "$ENV_FILE" <<EOF
# hillclimb-cam node config for MediaMTX path '${CAM_PATH}'. Generated by install.sh.
CAM_DEVICE=${CAM_DEVICE}
CAM_PATH=${CAM_PATH}
HUB_HOST=${HUB_HOST}
HUB_PORT=8890
CAM_INPUT_FORMAT=${CAM_INPUT_FORMAT}
CAM_ENCODER=${CAM_ENCODER}
CAM_W=${CAM_W}
CAM_H=${CAM_H}
CAM_FPS=${CAM_FPS}
CAM_BITRATE=${CAM_BITRATE}
SRT_LATENCY=200
HUB_WAIT=30
EOF
chmod 0644 "$ENV_FILE"
echo "Wrote $ENV_FILE"

# --- install scripts + units ------------------------------------------------
install -m 0755 "$REPO_DIR/bin/cam-stream.sh"   "$BIN_DST/cam-stream.sh"
install -m 0755 "$REPO_DIR/bin/cam-watchdog.sh" "$BIN_DST/cam-watchdog.sh"
sed "s/__RUN_USER__/${RUN_USER}/g" "$REPO_DIR/systemd/cam-stream@.service" > "$UNIT_DST/cam-stream@.service"
install -m 0644 "$REPO_DIR/systemd/cam-watchdog@.service" "$UNIT_DST/cam-watchdog@.service"

# --- persistent journal (so a reboot leaves a forensic trail) ---------------
# Storage=auto only uses /var/log/journal if the dir existed when journald
# started — a Pi easily ends up volatile with the dir present but unused. Force
# it with an explicit Storage=persistent drop-in.
if grep -qsiE '^[[:space:]]*Storage[[:space:]]*=[[:space:]]*persistent' \
     /etc/systemd/journald.conf /etc/systemd/journald.conf.d/*.conf 2>/dev/null; then
  echo "Persistent journald already configured."
else
  ask PERSIST "Enable persistent system logs (survive reboot)? (y/n)" y
  if [ "$PERSIST" = y ]; then
    install -d -m 0755 /etc/systemd/journald.conf.d
    printf '[Journal]\nStorage=persistent\n' > /etc/systemd/journald.conf.d/persistent.conf
    install -d -g systemd-journal -m 2755 /var/log/journal
    systemd-tmpfiles --create --prefix /var/log/journal 2>/dev/null || true
    systemctl restart systemd-journald 2>/dev/null || true
    journalctl --flush 2>/dev/null || true   # migrate now, don't wait for a reboot
    echo "Persistent journald enabled (Storage=persistent)."
  fi
fi

# --- enable + (re)start -----------------------------------------------------
# restart (not enable --now) so re-running the installer to change config
# actually reloads a service that is already running.
systemctl daemon-reload
systemctl enable "cam-stream@${CAM_PATH}" "cam-watchdog@${CAM_PATH}"
systemctl restart "cam-stream@${CAM_PATH}" "cam-watchdog@${CAM_PATH}"

echo; echo "== enabled cam-stream@${CAM_PATH} + cam-watchdog@${CAM_PATH} =="
sleep 3
systemctl --no-pager --lines=0 status "cam-stream@${CAM_PATH}" || true
echo
echo "Verify the feed reached the hub:"
echo "  $REPO_DIR/bin/test-publish.sh ${CAM_PATH} ${HUB_HOST}"
